Repository Gilly7CE/Carpet-Addons-Not-Found, pull requests merged in 2023-05, with the labels that each got.

#58 Refactor PistonBlock_MovableEmptyEndPortalFrameMixin to fix bug #57
  gradle.properties
  src/main/java/gillycarpetaddons/mixins/PistonBlock_MovableEmptyEndPortalFrameMixin.java
Labels: bug

#56 Add new option 'drop_as_items_on_explosion' to movableEmptyEndPortalFrames rule
  README.md
  src/main/java/gillycarpetaddons/GillyCarpetAddonsSettings.java
  src/main/java/gillycarpetaddons/mixins/PistonBlock_MovableEmptyEndPortalFrameMixin.java
  src/main/java/gillycarpetaddons/mixins/PistonExtensionBlock_MovableEmptyEndPortalFrameMixin.java
  src/main/resources/assets/gilly7ce-carpet-addons/lang/en_us.json
  src/main/resources/gilly7ce-carpet-addons.mixins.json
Labels: feature, improvement

#54 Add xpBubbleColumnInteraction rule
  README.md
  src/main/java/gillycarpetaddons/GillyCarpetAddonsSettings.java
  src/main/java/gillycarpetaddons/mixins/ExperienceOrbEntity_XpBubbleColumnInteractionMixin.java
  src/main/java/gillycarpetaddons/mixins/invokers/ExperienceOrbEntityInvokerMixin.java
  src/main/resources/assets/gilly7ce-carpet-addons/lang/en_us.json
  src/main/resources/gilly7ce-carpet-addons.mixins.json
Labels: feature

#53 Add creativePlayerOneHitKill rule
  README.md
  src/main/java/gillycarpetaddons/GillyCarpetAddonsSettings.java
  src/main/java/gillycarpetaddons/mixins/PlayerEntity_CreativePlayerOneHitKillMixin.java
  src/main/java/gillycarpetaddons/mixins/accessors/EntityAccessorMixin.java
  src/main/java/gillycarpetaddons/mixins/invokers/EntityInvokerMixin.java
  src/main/resources/assets/gilly7ce-carpet-addons/lang/en_us.json
  src/main/resources/gilly7ce-carpet-addons.mixins.json
Labels: feature

#51 Add dispensersPlaceEyesOfEnder and dispensersRemoveEyesOfEnder carpet rules
  README.md
  gradle.properties
  src/main/java/gillycarpetaddons/GillyCarpetAddonsSettings.java
  src/main/java/gillycarpetaddons/dispenser/DispenserItemUsageContext.java
  src/main/java/gillycarpetaddons/dispenser/GillyCarpetAddonDispenserBehaviors.java
  src/main/java/gillycarpetaddons/dispenser/behaviors/PlaceEyesOfEnderDispenserBehavior.java
  src/main/java/gillycarpetaddons/dispenser/behaviors/RemoveEyesOfEnderDispenserBehavior.java
  src/main/java/gillycarpetaddons/helpers/EndPortalFrameHelper.java
  src/main/java/gillycarpetaddons/mixins/DispenserBlock_GetCustomBehaviorMixin.java
  src/main/java/gillycarpetaddons/mixins/EndFrameBlock_EyeToggleMixin.java
  src/main/java/gillycarpetaddons/mixins/PistonBlock_MovableEmptyEndPortalFrameMixin.java
  src/main/resources/assets/gilly7ce-carpet-addons/lang/en_us.json
  src/main/resources/gilly7ce-carpet-addons.mixins.json
Labels: feature

#63 added rule "disablePhantomSpawningForCreativePlayers"
  README.md
  src/main/java/gillycarpetaddons/GillyCarpetAddonsSettings.java
  src/main/java/gillycarpetaddons/mixins/PhantomSpawnerMixin.java
  src/main/resources/assets/gilly7ce-carpet-addons/lang/en_us.json
Labels: bug, feature, high priority

#68 Fixed bug in dropEyesOfEnderFromEndPortalFrame rule from issue #30
  src/main/java/gillycarpetaddons/mixins/EndFrameBlock_EyeToggleMixin.java
Labels: bug, low priority

#70 Automated checks improvement & Update Gradle to latest version (8.1.1)
  .gitignore
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/resources/fabric.mod.json
  src/test/java/gillycarpetaddons/GillyCarpetAddonsServerTest.java
Labels: workflow

#73 Add code styling, documentation update for developer workflow & refactor mixin to be abstract
  .github/workflows/prbuild.yml
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  CODE_OF_CONDUCT.md
  README.md
  build.gradle
  gradle.properties
  src/main/java/gillycarpetaddons/GillyCarpetAddonsServer.java
  src/main/java/gillycarpetaddons/GillyCarpetAddonsSettings.java
  src/main/java/gillycarpetaddons/dispenser/DispenserItemUsageContext.java
  src/main/java/gillycarpetaddons/dispenser/GillyCarpetAddonDispenserBehaviors.java
  src/main/java/gillycarpetaddons/dispenser/behaviors/PlaceEyesOfEnderDispenserBehavior.java
  src/main/java/gillycarpetaddons/dispenser/behaviors/RemoveEyesOfEnderDispenserBehavior.java
  src/main/java/gillycarpetaddons/helpers/ChunkManagerHelper.java
  src/main/java/gillycarpetaddons/helpers/EndPortalFrameHelper.java
  src/main/java/gillycarpetaddons/helpers/ItemHelper.java
  src/main/java/gillycarpetaddons/helpers/ToolMaterialHelper.java
  src/main/java/gillycarpetaddons/instantmining/BlockBreakingSpeedRatioCalculator.java
  src/main/java/gillycarpetaddons/instantmining/CompositeInstantMiningRatioCalculator.java
  src/main/java/gillycarpetaddons/instantmining/HasteInstantMiningRatioCalculator.java
  src/main/java/gillycarpetaddons/instantmining/InstantMiningCarpetRuleAccessor.java
  src/main/java/gillycarpetaddons/instantmining/InstantMiningCarpetRuleKeys.java
  src/main/java/gillycarpetaddons/instantmining/InstantMiningRatioCalculator.java
  src/main/java/gillycarpetaddons/instantmining/ToolInstantMiningRatioCalculator.java
  src/main/java/gillycarpetaddons/lists/BlockList.java
  src/main/java/gillycarpetaddons/mixins/AbstractClientPlayerEntity_InstantMineMixin.java
  src/main/java/gillycarpetaddons/mixins/DispenserBlock_GetCustomBehaviorMixin.java
  src/main/java/gillycarpetaddons/mixins/EndFrameBlock_EyeToggleMixin.java
  src/main/java/gillycarpetaddons/mixins/ExperienceOrbEntity_XpBubbleColumnInteractionMixin.java
  src/main/java/gillycarpetaddons/mixins/PhantomSpawnerMixin.java
  src/main/java/gillycarpetaddons/mixins/PistonBlock_MovableEmptyEndPortalFrameMixin.java
  src/main/java/gillycarpetaddons/mixins/PistonBlock_MovableSpawnersMixin.java
  src/main/java/gillycarpetaddons/mixins/PistonExtensionBlock_MovableEmptyEndPortalFrameMixin.java
  src/main/java/gillycarpetaddons/mixins/PlayerEntity_CreativePlayerOneHitKillMixin.java
  src/main/java/gillycarpetaddons/mixins/ServerChunkManager_PhantomsObeyHostileMobCapMixin.java
  src/main/java/gillycarpetaddons/mixins/ServerPlayerEntity_InstantMineMixin.java
  src/main/java/gillycarpetaddons/mixins/ServerPlayerEntity_SpectatorPlayersUsePortalsMixin.java
  src/main/java/gillycarpetaddons/mixins/accessors/EntityAccessorMixin.java
  src/main/java/gillycarpetaddons/mixins/invokers/EntityInvokerMixin.java
  src/main/java/gillycarpetaddons/mixins/invokers/ExperienceOrbEntityInvokerMixin.java
  src/main/java/gillycarpetaddons/mixins/invokers/SpawnHelperInfoInvokerMixin.java
  src/main/java/gillycarpetaddons/ruleobservers/movableSpawnerRuleObserver.java
  src/main/resources/assets/gilly7ce-carpet-addons/lang/en_us.json
  src/main/resources/fabric.mod.json
  src/test/java/gillycarpetaddons/GillyCarpetAddonsServerTest.java
Labels: documentation, improvement

#74 Replace netherite instant mining mixins with single mixin
  src/main/java/gillycarpetaddons/instantmining/BlockBreakingSpeedRatioCalculator.java
  src/main/java/gillycarpetaddons/mixins/AbstractClientPlayerEntity_InstantMineMixin.java
  src/main/java/gillycarpetaddons/mixins/PlayerEntity_InstantMineMixin.java
  src/main/java/gillycarpetaddons/mixins/ServerPlayerEntity_InstantMineMixin.java
  src/main/resources/gilly7ce-carpet-addons.mixins.json
Labels: improvement

#75 Update carpet to latest 1.19.3 version (1.4.96)
  gradle.properties
  src/main/resources/fabric.mod.json
Labels: dependencies

#77 Update minecraft version to 1.18.2
  gradle.properties
  src/main/java/gillycarpetaddons/GillyCarpetAddonsServer.java
  src/main/java/gillycarpetaddons/GillyCarpetAddonsSettings.java
  src/main/java/gillycarpetaddons/dispenser/behaviors/RemoveEyesOfEnderDispenserBehavior.java
  src/main/java/gillycarpetaddons/lists/BlockList.java
  src/main/java/gillycarpetaddons/mixins/DispenserBlock_GetCustomBehaviorMixin.java
  src/main/java/gillycarpetaddons/mixins/PhantomSpawnerMixin.java
  src/main/java/gillycarpetaddons/mixins/ServerPlayerEntity_SpectatorPlayersUsePortalsMixin.java
  src/main/java/gillycarpetaddons/ruleobservers/movableSpawnerRuleObserver.java
  src/main/resources/assets/gilly7ce-carpet-addons/lang/en_us.json
  src/main/resources/fabric.mod.json
Labels: mcversion

#79 Update minecraft version to 1.17.1
  README.md
  build.gradle
  gradle.properties
  src/main/java/gillycarpetaddons/GillyCarpetAddonsSettings.java
  src/main/java/gillycarpetaddons/helpers/ChunkManagerHelper.java
  src/main/java/gillycarpetaddons/mixins/PhantomSpawnerMixin.java
  src/main/java/gillycarpetaddons/mixins/PlayerEntity_CreativePlayerOneHitKillMixin.java
  src/main/java/gillycarpetaddons/mixins/ServerChunkManager_PhantomsObeyHostileMobCapMixin.java
  src/main/java/gillycarpetaddons/mixins/accessors/EntityAccessorMixin.java
  src/main/java/gillycarpetaddons/mixins/invokers/EntityInvokerMixin.java
  src/main/java/gillycarpetaddons/mixins/invokers/SpawnHelperInfoInvokerMixin.java
  src/main/resources/fabric.mod.json
  src/main/resources/gilly7ce-carpet-addons.mixins.json
  src/test/java/gillycarpetaddons/GillyCarpetAddonsServerTest.java
Labels: mcversion

#97 Fix `creativePlayerOneHitKill` from destroying item frames
  gradle.properties
  src/main/java/gillycarpetaddons/mixins/PlayerEntity_CreativePlayerOneHitKillMixin.java
Labels: bug

#94 Flower replace rule
  src/main/java/gillycarpetaddons/GillyCarpetAddonsSettings.java
  src/main/java/gillycarpetaddons/mixins/FlowerBlock_ReplaceFlowersMixin.java
  src/main/java/gillycarpetaddons/mixins/TallFlowerBlock_ReplaceFlowersMixin.java
  src/main/resources/assets/gilly7ce-carpet-addons/lang/en_us.json
  src/main/resources/gilly7ce-carpet-addons.mixins.json
Labels: feature

#109 [RULE] - Disable mob spawning per dimension
  README.md
  src/main/java/carpetaddonsnotfound/CarpetAddonsNotFoundSettings.java
  src/main/java/carpetaddonsnotfound/mixins/SpawnHelper_disableMobSpawningInMixin.java
  src/main/resources/assets/carpet-addons-not-found/lang/en_us.json
  src/main/resources/carpet-addons-not-found.mixins.json
Labels: feature

#112 Carpet rule for creating mobs with no AI using spawn eggs
  README.md
  src/main/java/carpetaddonsnotfound/CarpetAddonsNotFoundSettings.java
  src/main/java/carpetaddonsnotfound/mixins/SpawnEggItem_SpawnEggsSpawnMobsWithNoAIMixin.java
  src/main/resources/assets/carpet-addons-not-found/lang/en_us.json
  src/main/resources/carpet-addons-not-found.mixins.json
Labels: feature

#122 Improve code styling rules for project with IntelliJ IDEA
  .idea/codeStyles/Project.xml
  src/main/java/carpetaddonsnotfound/helpers/EndPortalFrameHelper.java
  src/main/java/carpetaddonsnotfound/mixins/PistonBlock_MovableEmptyEndPortalFrameMixin.java
  src/main/java/carpetaddonsnotfound/mixins/ServerPlayerEntity_SpectatorPlayersUsePortalsMixin.java
  src/main/java/carpetaddonsnotfound/mixins/SpawnHelper_DisableMobSpawningInMixin.java
  src/main/resources/assets/carpet-addons-not-found/lang/en_us.json
  src/main/resources/carpet-addons-not-found.mixins.json
Labels: improvement

#116 [RULE] - PortalSpectatorDelay
  README.md
  src/main/java/carpetaddonsnotfound/CarpetAddonsNotFoundSettings.java
  src/main/java/carpetaddonsnotfound/mixins/PlayerEntity_PortalSpectatorDelayMixin.java
  src/main/java/carpetaddonsnotfound/validators/OneHourMaxDelayLimit.java
  src/main/resources/assets/carpet-addons-not-found/lang/en_us.json
  src/main/resources/carpet-addons-not-found.mixins.json
  src/main/resources/fabric.mod.json
Labels: feature

#121 Bug Fix - Use proper mod name text in logo
  src/main/resources/assets/carpet-addons-not-found/icon.png
Labels: bug

#129 Refactor PhantomSpawnerMixin to be more compatible with other mods
  README.md
  src/main/java/carpetaddonsnotfound/mixins/PhantomSpawnerMixin.java
  src/main/java/carpetaddonsnotfound/mixins/ServerChunkManager_PhantomsObeyHostileMobCapMixin.java
  src/main/java/carpetaddonsnotfound/phantomspawning/DefaultHandler.java
  src/main/java/carpetaddonsnotfound/phantomspawning/DisableForCreativePlayersHandler.java
  src/main/java/carpetaddonsnotfound/phantomspawning/DisableInMushroomFieldsHandler.java
  src/main/java/carpetaddonsnotfound/phantomspawning/ObeyHostileMobCapHandler.java
  src/main/java/carpetaddonsnotfound/phantomspawning/PhantomSpawningHandler.java
  src/main/java/carpetaddonsnotfound/phantomspawning/PhantomSpawningHandlerHelper.java
  src/main/resources/assets/carpet-addons-not-found/lang/en_us.json
Labels: bug, improvement
