Repository Gilly7CE/Carpet-Addons-Not-Found, pull requests merged in 2023-04, with the labels that each got.

#4 Project setup and instant mining with netherite tools carpet rules
  .gitignore
  README.md
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/gillycarpetaddons/GillyCarpetAddonsServer.java
  src/main/java/gillycarpetaddons/GillyCarpetAddonsSettings.java
  src/main/java/gillycarpetaddons/helpers/ItemHelper.java
  src/main/java/gillycarpetaddons/helpers/ToolMaterialHelper.java
  src/main/java/gillycarpetaddons/instantmining/BlockBreakingSpeedRatioCalculator.java
  src/main/java/gillycarpetaddons/instantmining/CompositeInstantMiningRatioCalculator.java
  src/main/java/gillycarpetaddons/instantmining/HasteInstantMiningRatioCalculator.java
  src/main/java/gillycarpetaddons/instantmining/InstantMiningCarpetRuleAccessor.java
  src/main/java/gillycarpetaddons/instantmining/InstantMiningCarpetRuleKeys.java
  src/main/java/gillycarpetaddons/instantmining/InstantMiningRatioCalculator.java
  src/main/java/gillycarpetaddons/instantmining/ToolInstantMiningRatioCalculator.java
  src/main/java/gillycarpetaddons/lists/BlockList.java
  src/main/java/gillycarpetaddons/mixins/AbstractClientPlayerEntity_InstantMineMixin.java
  src/main/java/gillycarpetaddons/mixins/ServerPlayerEntity_InstantMineMixin.java
  src/main/resources/assets/gilly7ce-carpet-addons/icon.png
  src/main/resources/assets/gilly7ce-carpet-addons/lang/en_us.json
  src/main/resources/fabric.mod.json
  src/main/resources/gilly7ce-carpet-addons.mixins.json
Labels: feature

#6 Add workflows for PR's, pushing to the main branch and publishing
  .github/workflows/mainbuild.yml
  .github/workflows/prbuild.yml
  .github/workflows/publish.yml
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
Labels: workflow

#10 Use version 3.2 instead of 3 for mc-publish
  .github/workflows/publish.yml
Labels: bug, workflow

#13 Add write permissions to publish.yml
  .github/workflows/publish.yml
Labels: bug, workflow

#17 Add contribution documentation to README.md
  README.md
Labels: documentation

#23 Update README.md
  README.md
Labels: documentation

#25 Added dropEyesOfEnderFromEndPortalFrame rule as requested in issue #20.
  src/main/java/gillycarpetaddons/GillyCarpetAddonsSettings.java
  src/main/java/gillycarpetaddons/mixins/EndFrameBlock_EyeToggleMixin.java
  src/main/resources/assets/gilly7ce-carpet-addons/lang/en_us.json
  src/main/resources/gilly7ce-carpet-addons.mixins.json
Labels: feature

#29 Added phantomsObeyHostileMobCap rule
  README.md
  src/main/java/gillycarpetaddons/GillyCarpetAddonsSettings.java
  src/main/java/gillycarpetaddons/helpers/ChunkManagerHelper.java
  src/main/java/gillycarpetaddons/mixins/PhantomSpawner_PhantomsObeyHostileMobCapMixin.java
  src/main/java/gillycarpetaddons/mixins/ServerChunkManager_PhantomsObeyHostileMobCapMixin.java
  src/main/java/gillycarpetaddons/mixins/invokers/SpawnHelperInfoInvokerMixin.java
  src/main/resources/assets/gilly7ce-carpet-addons/lang/en_us.json
  src/main/resources/gilly7ce-carpet-addons.mixins.json
Labels: feature

#38 Add moveable empty end portal frames
  README.md
  src/main/java/gillycarpetaddons/GillyCarpetAddonsSettings.java
  src/main/java/gillycarpetaddons/mixins/PistonBlock_MovableEmptyEndPortalFrameMixin.java
  src/main/resources/assets/gilly7ce-carpet-addons/lang/en_us.json
  src/main/resources/gilly7ce-carpet-addons.mixins.json
Labels: feature

#42 Add movableSpawners rule
  README.md
  src/main/java/gillycarpetaddons/GillyCarpetAddonsServer.java
  src/main/java/gillycarpetaddons/GillyCarpetAddonsSettings.java
  src/main/java/gillycarpetaddons/mixins/PistonBlock_MovableSpawnersMixin.java
  src/main/java/gillycarpetaddons/ruleobservers/movableSpawnerRuleObserver.java
  src/main/resources/assets/gilly7ce-carpet-addons/lang/en_us.json
  src/main/resources/gilly7ce-carpet-addons.mixins.json
Labels: feature
