Repository Gilly7CE/Carpet-Addons-Not-Found, pull requests merged in 2023-06, with the labels that each got.

#132 Fix `spectatorPlayersUsePortals` not showing portal nausea affect when `portalSpectatorDelay` is at a value greater than 1
  src/main/java/carpetaddonsnotfound/fakes/ClientPlayPacketListenerInterface.java
  src/main/java/carpetaddonsnotfound/mixins/ClientPlayNetworkHandler_SpectatorPlayersUsePortalsMixin.java
  src/main/java/carpetaddonsnotfound/mixins/NetworkState_SpectatorPlayersUsePortalsMixin.java
  src/main/java/carpetaddonsnotfound/mixins/ServerPlayerEntity_SpectatorPlayersUsePortalsMixin.java
  src/main/java/carpetaddonsnotfound/network/packets/SpectatorPlayerInPortalBlockS2CPacket.java
  src/main/resources/carpet-addons-not-found.mixins.json
Labels: bug

#139 Allways pick flowers from pots
  README.md
  src/main/java/carpetaddonsnotfound/CarpetAddonsNotFoundSettings.java
  src/main/java/carpetaddonsnotfound/mixins/FlowerPotBlock_PickFlowersFromPotsMixin.java
  src/main/resources/assets/carpet-addons-not-found/lang/en_us.json
  src/main/resources/carpet-addons-not-found.mixins.json
Labels: feature

#144 Add automation to populate wiki with carpet rule definitions & fix bug with `movableSpawners` rule setting
  .github/actions/update-wiki/action.yml
  .github/workflows/justupdatewiki.yml
  .github/workflows/publish.yml
  README.md
  src/main/java/carpetaddonsnotfound/CarpetAddonsNotFoundServer.java
  src/main/java/carpetaddonsnotfound/CarpetAddonsNotFoundSettings.java
  src/main/java/carpetaddonsnotfound/ruleobservers/MovableBlockEntitiesRuleObserver.java
  src/main/java/carpetaddonsnotfound/ruleobservers/movableSpawnerRuleObserver.java
  src/main/java/carpetaddonsnotfound/validators/RequiresMovableBlockEntities.java
  src/main/resources/assets/carpet-addons-not-found/lang/en_us.json
  src/main/resources/fabric.mod.json
Labels: documentation, workflow

#159 Fix `spectatorPlayersUsePortals` crashing client side when running on multiplayer server
  gradle.properties
  src/main/java/carpetaddonsnotfound/CarpetAddonsNotFoundServer.java
  src/main/java/carpetaddonsnotfound/CarpetAddonsNotFoundSettings.java
  src/main/java/carpetaddonsnotfound/fakes/ClientPlayPacketListenerInterface.java
  src/main/java/carpetaddonsnotfound/mixins/ClientPlayNetworkHandler_SpectatorPlayersUsePortalsMixin.java
  src/main/java/carpetaddonsnotfound/mixins/NetworkState_SpectatorPlayersUsePortalsMixin.java
  src/main/java/carpetaddonsnotfound/mixins/ServerPlayerEntity_SpectatorPlayersUsePortalsMixin.java
  src/main/java/carpetaddonsnotfound/mixins/network/ClientPlayNetworkHandler_CustomPacketsMixin.java
  src/main/java/carpetaddonsnotfound/mixins/network/ServerPlayNetworkHandler_CustomPacketsMixin.java
  src/main/java/carpetaddonsnotfound/network/CarpetAddonsNotFoundClient.java
  src/main/java/carpetaddonsnotfound/network/ClientNetworkHandler.java
  src/main/java/carpetaddonsnotfound/network/NbtCompoundKeys.java
  src/main/java/carpetaddonsnotfound/network/ServerNetworkHandler.java
  src/main/java/carpetaddonsnotfound/network/packets/SpectatorPlayerInPortalBlockS2CPacket.java
  src/main/resources/carpet-addons-not-found.mixins.json
Labels: bug

#158 Add replaceFlowersInPots rule
  src/main/java/carpetaddonsnotfound/CarpetAddonsNotFoundSettings.java
  src/main/java/carpetaddonsnotfound/mixins/FlowerPotBlock_ReplaceFlowersInPots.java
  src/main/resources/assets/carpet-addons-not-found/lang/en_us.json
  src/main/resources/carpet-addons-not-found.mixins.json
Labels: feature
